alerts:
  batch_strategy: smart_batch
  max_daily_alerts: 10
  notification_channels:
  - pushover
  - notion
api_limits:
  finnhub:
    calls_per_day: 1000
    calls_per_minute: 60
  newdata:
    calls_per_day: 200
  newsapi:
    articles_per_credit: 10
    calls_per_day: 100
  openai:
    max_requests_per_day: 50
    max_tokens_per_request: 1000
app:
  debug: false
  log_level: INFO
  name: MarketMan
  version: 1.0.0
database:
  path: data/marketman.db
  type: sqlite
filters:
  exclude_broad_market_unless_no_alternative: true
  max_etfs_per_signal: 5
  require_specialized_etf_preference: true
integrations:
  gmail:
    credentials_path: config/credentials/gmail_credentials.json
    enabled: true
    poll_interval_minutes: 5
    token_path: config/credentials/gmail_token.pickle
  notion:
    database_id: ''
    enabled: true
    update_interval_minutes: 10
  pushover:
    api_token: akjhp6gm868mieuixabjum98tbbq29
    confidence_threshold: 7
    enabled: true
    priority_settings:
      high_confidence: 0
      low_confidence: -1
      medium_confidence: 0
      risk_warnings: 1
      system_alerts: 1
    rate_limit_per_hour: 10
    risk_warnings_enabled: true
    user_token: ur914z6b94u72hk8nxc3qo13ift4aw
logging:
  backup_count: 5
  file_enabled: true
  log_file: logs/marketman.log
  max_file_size_mb: 10
min_confidence_threshold: 7
min_mentions_for_etf: 2
news_ingestion:
  advanced_filtering:
    min_relevance_score: 0.3
    min_sentiment_strength: 0.2
    min_ticker_count: 1
    require_multiple_tickers: false
  batching:
    max_batch_wait_time: 300
    max_headlines_per_batch: 5
    min_batch_size: 2
  duplicate_detection:
    enabled: true
    similarity_threshold: 0.8
    time_window_hours: 24
  keywords:
  - ETF
  - SPY
  - QQQ
  - DIA
  - interest rate
  - Fed
  - Federal Reserve
  - earnings
  - cut
  - downgrade
  - upgrade
  - SEC
  - lawsuit
  - merger
  - acquisition
  - IPO
  - bankruptcy
  - dividend
  - split
  - guidance
  - forecast
  - analyst
  - rating
  - target
  - volatility
  - VIX
  - VIXY
  - VXX
  market_hours:
    end: '16:00'
    start: 09:30
    timezone: America/New_York
  max_daily_ai_calls: 50
  max_daily_headlines: 20
  max_monthly_ai_budget: 20.0
  multi_source_validation:
    enabled: true
    source_categories:
      Ars Technica: tech
      Bloomberg: financial
      CNBC: financial
      Financial Times: financial
      MarketWatch: financial
      Reuters: financial
      Seeking Alpha: financial
      TechCrunch: tech
      Yahoo Finance: financial
      unknown: general
    source_weights:
      Ars Technica: 2
      Bloomberg: 5
      CNBC: 4
      Financial Times: 5
      MarketWatch: 4
      Reuters: 5
      Seeking Alpha: 3
      TechCrunch: 3
      Yahoo Finance: 3
      unknown: 1
  tracked_tickers:
  - BOTZ
  - ROBO
  - IRBO
  - ARKQ
  - SMH
  - SOXX
  - ITA
  - XAR
  - DFEN
  - PPA
  - URNM
  - NLR
  - URA
  - ICLN
  - TAN
  - QCLN
  - PBW
  - LIT
  - REMX
  - VIXY
  - VXX
  - SQQQ
  - SPXS
  - SPY
  - QQQ
  - DIA
  - IWM
options:
  max_trade_size: 1000
  max_trades_per_day: 5
  profit_target_percent: 1.5
  scalping_enabled: false
  stop_loss_percent: 1.0
  symbols:
  - QQQ
  - SPY
pattern_recognition:
  enabled: true
  min_pattern_confidence: 0.7
  supported_patterns:
  - double_top
  - double_bottom
  - head_and_shoulders
  - breakout
  - breakdown
  - support_resistance
  - volume_spike
performance:
  dashboard_enabled: true
  tracking_enabled: true
  update_interval_minutes: 15
risk:
  max_daily_loss: 0.05
  max_daily_loss_percent: 3.0
  max_kelly_fraction: 0.25
  max_position_size: 0.02
  max_position_size_percent: 5.0
  position_sizing_enabled: true
  stop_loss_percent: 2.0
signals:
  etf:
    conviction_threshold: 0.7
    enabled: true
    max_signals_per_day: 10
    update_interval_minutes: 5
  news:
    enabled: true
    gpt_analysis_enabled: true
    max_news_items_per_analysis: 50
    sentiment_threshold: 0.6
technical_analysis:
  enabled: true
  indicators:
  - rsi
  - macd
  - bollinger
